ERROR:root:2018-03-19 14:26:22.375000: 400UC83400 16113244
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 69, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 120, in runTests
    ReturnLossTest(self)
  File "C:\123\RFBCheck\Tests\rloss_test.py", line 25, in __init__
    self.returnLossTest()
  File "C:\123\RFBCheck\Tests\rloss_test.py", line 30, in returnLossTest
    if currRloss > rlossmax:
TypeError: unorderable types: float() > NoneType()
ERROR:root:2018-03-20 17:11:50.234375: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 69, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 110, in runTests
    BitAlarmTest(self, self.currParent)
  File "C:\123\RFBCheck\Tests\bitAlarm_test.py", line 23, in __init__
    self.listSettings = self.mainParent.listSettings
AttributeError: 'BitAlarmTest' object has no attribute 'mainParent'
ERROR:root:2018-04-15 15:05:51: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 69, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 125, in runTests
    DetectorTest(self)
NameError: name 'DetectorTest' is not defined
ERROR:root:2018-04-15 15:06:57.328125: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 29, in __init__
    self.detectorTest(self.freqDl)
AttributeError: 'DetectorTest' object has no attribute 'detectorTest'
ERROR:root:2018-04-15 15:14:42.718750: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 30, in __init__
    self.detectorTest(self.freqDl)
AttributeError: 'DetectorTest' object has no attribute 'detectorTest'
ERROR:root:2018-04-15 16:06:07.500000: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 66, in run
    self.readAdemSettings()
  File "C:\123\RFBCheck\Tests\testController.py", line 289, in readAdemSettings
    lenNewArr = int(row.get(None)[3])
TypeError: 'NoneType' object is not subscriptable
ERROR:root:2018-04-15 16:06:31.218750: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 66, in run
    self.readAdemSettings()
  File "C:\123\RFBCheck\Tests\testController.py", line 289, in readAdemSettings
    lenNewArr = int(row.get(None)[3])
TypeError: 'NoneType' object is not subscriptable
ERROR:root:2018-04-15 16:07:43.890625: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 66, in run
    self.readAdemSettings()
  File "C:\123\RFBCheck\Tests\testController.py", line 289, in readAdemSettings
    lenNewArr = int(row.get(None)[3])
TypeError: 'NoneType' object is not subscriptable
ERROR:root:2018-04-15 16:08:29.859375: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 66, in run
    self.readAdemSettings()
  File "C:\123\RFBCheck\Tests\testController.py", line 289, in readAdemSettings
    lenNewArr = int(row.get(None)[3])
TypeError: 'NoneType' object is not subscriptable
ERROR:root:2018-04-15 16:09:02.218750: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 66, in run
    self.readAdemSettings()
  File "C:\123\RFBCheck\Tests\testController.py", line 289, in readAdemSettings
    lenNewArr = int(row.get(None)[3])
TypeError: 'NoneType' object is not subscriptable
ERROR:root:2018-04-15 16:10:52.437500: RA00057 xxxx
Traceback (most recent call last):
  File "C:/123/RFBCheck\Tests\testController.py", line 66, in run
    self.readAdemSettings()
  File "C:/123/RFBCheck\Tests\testController.py", line 289, in readAdemSettings
    lenNewArr = int(row.get(None)[3])
TypeError: 'NoneType' object is not subscriptable
ERROR:root:2018-04-15 16:11:53.250000: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 66, in run
    self.readAdemSettings()
  File "C:\123\RFBCheck\Tests\testController.py", line 289, in readAdemSettings
    lenNewArr = int(row.get(None)[3])
TypeError: 'NoneType' object is not subscriptable
ERROR:root:2018-04-15 16:14:31.234375: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 66, in run
    self.readAdemSettings()
  File "C:\123\RFBCheck\Tests\testController.py", line 289, in readAdemSettings
    lenNewArr = int(row.get(None)[3])
TypeError: 'NoneType' object is not subscriptable
ERROR:root:2018-04-15 16:14:53.859375: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 66, in run
    self.readAdemSettings()
  File "C:\123\RFBCheck\Tests\testController.py", line 289, in readAdemSettings
    lenNewArr = int(row.get(None)[3])
TypeError: 'NoneType' object is not subscriptable
ERROR:root:2018-04-15 16:15:06.078125: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 66, in run
    self.readAdemSettings()
  File "C:\123\RFBCheck\Tests\testController.py", line 289, in readAdemSettings
    lenNewArr = int(row.get(None)[3])
TypeError: 'NoneType' object is not subscriptable
ERROR:root:2018-04-15 16:16:38.500000: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 66, in run
    self.readAdemSettings()
  File "C:\123\RFBCheck\Tests\testController.py", line 289, in readAdemSettings
    lenNewArr = int(row.get(None)[3])
TypeError: 'NoneType' object is not subscriptable
ERROR:root:2018-04-15 16:16:52.953125: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 66, in run
    self.readAdemSettings()
  File "C:\123\RFBCheck\Tests\testController.py", line 289, in readAdemSettings
    lenNewArr = int(row.get(None)[3])
TypeError: 'NoneType' object is not subscriptable
ERROR:root:2018-04-16 08:43:14.093084: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 31, in __init__
    self.forwardTest(self.freqDl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 51, in forwardTest
    print("Anch.: %s: Det.: %s") % (anchor, rx)
TypeError: unsupported operand type(s) for %: 'NoneType' and 'tuple'
ERROR:root:2018-04-16 08:44:31.218084: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 31, in __init__
    self.forwardTest(self.freqDl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 51, in forwardTest
    print("Anch.: %s: Det.: %s") % (str(anchor), str(rx))
TypeError: unsupported operand type(s) for %: 'NoneType' and 'tuple'
ERROR:root:2018-04-16 08:50:13.655584: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 31, in __init__
    self.forwardTest(self.freqDl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 52, in forwardTest
    print("Anch.: %s: Det.: %s") % (str(anchor), str(detector))
TypeError: unsupported operand type(s) for %: 'NoneType' and 'tuple'
ERROR:root:2018-04-16 11:18:42.921209: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 31, in __init__
    self.forwardTest(self.freqUl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 46, in forwardTest
    self.preTest()
  File "C:\123\RFBCheck\Tests\detector_test.py", line 41, in preTest
    self.send(self, 'SetAlc', i + '00FF')
TypeError: send() takes 3 positional arguments but 4 were given
ERROR:root:2018-04-16 12:44:24.311834: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 32, in __init__
    self.forwardTest(self.freqUl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 50, in forwardTest
    anchor = int(rx[rx.find(self.reqAddr.get(addrAnch)) + 4: rx.find(self.reqAddr.get(addrAnch)) + 8], 16)
AttributeError: 'bool' object has no attribute 'find'
ERROR:root:2018-04-16 14:23:27.671209: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 30, in __init__
    self.forwardTest(self.freqDl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 81, in forwardTest
    print(len(arrDetector))
TypeError: object of type 'NoneType' has no len()
ERROR:root:2018-04-16 14:40:18.624334: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 30, in __init__
    self.forwardTest(self.freqDl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 82, in forwardTest
    for i in arrDetector.reverse():
TypeError: 'NoneType' object is not iterable
ERROR:root:2018-04-16 14:42:48.452459: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 30, in __init__
    self.forwardTest(self.freqDl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 82, in forwardTest
    for i in arrDetector.reverse():
TypeError: 'NoneType' object is not iterable
ERROR:root:2018-04-16 14:46:59.358709: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 30, in __init__
    self.forwardTest(self.freqDl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 83, in forwardTest
    for i in arrDetector.reverse():
TypeError: 'NoneType' object is not iterable
ERROR:root:2018-04-16 15:46:25.077459: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 31, in __init__
    self.reversTest(self.freqDl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 112, in reversTest
    anchor = int(rx[rx.find(self.reqAddr.get(addrAnch)) + 4: rx.find(self.reqAddr.get(addrAnch)) + 8], 16)
AttributeError: 'bool' object has no attribute 'find'
ERROR:root:2018-04-16 15:50:01.452459: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 31, in __init__
    self.reversTest(self.freqDl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 112, in reversTest
    anchor = int(rx[rx.find(self.reqAddr.get(addrAnch)) + 4: rx.find(self.reqAddr.get(addrAnch)) + 8], 16)
AttributeError: 'bool' object has no attribute 'find'
ERROR:root:2018-04-17 07:45:52.468750: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 31, in __init__
    self.reversTest(self.freqDl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 127, in reversTest
    detector = int(rx[rx.find(self.reqAddr.get(addrDet)) + 12: rx.find(self.reqAddr.get(addrDet)) + 16], 16)
AttributeError: 'bool' object has no attribute 'find'
ERROR:root:2018-04-17 08:32:50.171875: RA00297 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 30, in __init__
    self.forwardTest(self.freqDl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 45, in forwardTest
    str(int(self.parent.saAtten.text()) + abs(float(self.getOffset(freq)))))
AttributeError: 'builtin_function_or_method' object has no attribute 'saAtten'
ERROR:root:2018-04-17 09:41:36.578125: RA00057 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 126, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 30, in __init__
    self.forwardTest(self.freqDl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 44, in forwardTest
    self.setNaOffset(freq)
AttributeError: 'DetectorTest' object has no attribute 'setNaOffset'
ERROR:root:2018-04-21 22:28:23.609375: RA002900 18040652
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 70, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 121, in runTests
    ReturnLossTest(self)
  File "C:\123\RFBCheck\Tests\rloss_test.py", line 25, in __init__
    self.returnLossTest()
  File "C:\123\RFBCheck\Tests\rloss_test.py", line 30, in returnLossTest
    if currRloss > rlossmax:
TypeError: unorderable types: float() > NoneType()
ERROR:root:2018-04-22 20:15:32.156250: RA00297 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 60, in run
    self.whatConn = self.checkUlDl()
  File "C:\123\RFBCheck\Tests\testController.py", line 207, in checkUlDl
    self.instr.gen.write(":OUTP:STAT ON")
AttributeError: 'NoneType' object has no attribute 'write'
ERROR:root:2018-04-24 21:33:42.500000: RA002900 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 60, in run
    self.whatConn = self.checkUlDl()
  File "C:\123\RFBCheck\Tests\testController.py", line 214, in checkUlDl
    gain = float(getAvgGain(self))
  File "C:\123\RFBCheck\Equip\equip.py", line 117, in getAvgGain
    gainArr.append(float(testController.instr.sa.query("CALC:MARK:Y?")) + float(parent.genAtten.text))
TypeError: float() argument must be a string or a number, not 'builtin_function_or_method'
ERROR:root:2018-04-25 02:58:59.125000: RA00297 18040718
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 73, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 129, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 33, in __init__
    self.forwardTest(self.freqUl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 54, in forwardTest
    anchor = int(rx[rx.find(self.reqAddr.get(addrAnch)) + 4: rx.find(self.reqAddr.get(addrAnch)) + 8], 16)
AttributeError: 'NoneType' object has no attribute 'find'
ERROR:root:2018-04-25 07:04:39.218750: RA002900 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 73, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 129, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 30, in __init__
    self.forwardTest(self.freqDl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 53, in forwardTest
    rx = self.send(addrAnch, self.reqAddr.get(addrAnch))
  File "C:\123\RFBCheck\Tests\detector_test.py", line 195, in send
    print(namePar)
OSError: [Errno 22] Invalid argument
ERROR:root:2018-04-25 07:05:05.359375: RA002900 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 73, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 129, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 30, in __init__
    self.forwardTest(self.freqDl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 53, in forwardTest
    rx = self.send(addrAnch, self.reqAddr.get(addrAnch))
  File "C:\123\RFBCheck\Tests\detector_test.py", line 195, in send
    print(namePar)
OSError: [Errno 22] Invalid argument
ERROR:root:2018-05-07 08:06:13.119504: RA00297 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 73, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 129, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 30, in __init__
    self.forwardTest(self.freqDl)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 54, in forwardTest
    anchor = int(rx[rx.find(self.reqAddr.get(addrAnch)) + 4: rx.find(self.reqAddr.get(addrAnch)) + 8], 16)
AttributeError: 'NoneType' object has no attribute 'find'
ERROR:root:2018-05-07 14:44:53.478879: RA002900 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 73, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 129, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 34, in __init__
    print(rx[rx.find(i) + len(str(i)): len(rx) - 2])
TypeError: Can't convert 'int' object to str implicitly
ERROR:root:2018-05-07 15:21:10.978879: RA002900 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 73, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 129, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 34, in __init__
    rx = self.send(i, int(addr) + 10)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 180, in send
    toSend = self.prefToSend + addr
TypeError: Can't convert 'int' object to str implicitly
ERROR:root:2018-05-07 15:22:51.010129: RA002900 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 73, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 129, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 35, in __init__
    minLimit = int(rx[rx.find(addr) + len(addr): (len(rx) - 2)/2], 16)
TypeError: slice indices must be integers or None or have an __index__ method
ERROR:root:2018-05-07 15:24:44.619504: RA002900 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 73, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 129, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 35, in __init__
    minLimit = int(rx[rx.find(addr) + len(addr): (len(rx) - 2)/2], 16)
TypeError: slice indices must be integers or None or have an __index__ method
ERROR:root:2018-05-07 15:40:45.932004: RA002900 xxxx
Traceback (most recent call last):
  File "C:\123\RFBCheck\Tests\testController.py", line 73, in run
    self.runTests()
  File "C:\123\RFBCheck\Tests\testController.py", line 129, in runTests
    DetectorTest(self)
  File "C:\123\RFBCheck\Tests\detector_test.py", line 37, in __init__
    minLimit = int(hexStr[:len(hexStr)/2], 16)
TypeError: slice indices must be integers or None or have an __index__ method
